### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Klay4** [Bluethefurry/RottenV-Remade-Basic#6]
Authenticating server license key…
Server license key authentication succeeded. Welcome!
cfx> Sending heartbeat to live-internal.fivem.net:30110
restarestart sessionmanager
Stopping resource sessionmanager
cfx> Started resource sessionmanager
Connecting: Nerf_Klay4
Sending heartbeat to live-internal.fivem.net:30110
InvokeNative: execution failed: Argument at index 0 was null.
Error running system event handling function for resource RottenV-Remade-Basic-master: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: Execution of native 00000000406b4b20 in script host failed.
stack traceback:
[C]: in upvalue ‘_in’
citizen:/scripting/lua/natives_server.lua:156: in function ‘GetPlayerName’
server/gui/notifications_s.lua:16: in upvalue ‘handler’
citizen:/scripting/lua/scheduler.lua:175: in function citizen:/scripting/lua/scheduler.lua:174
stack traceback:
[C]: in function ‘error’
citizen:/scripting/lua/scheduler.lua:41: in field ‘CreateThreadNow’
citizen:/scripting/lua/scheduler.lua:174: in function citizen:/scripting/lua/scheduler.lua:138

-------------------------------------------------------------------------------------------------------------------

Please Help
If I try to connect to the server, the loading is infinite

**Comment by Bluethefurry** [comment]
i already responded to your forum topic, this is intended behaviour, the "loading is infinite" issue is your fault.
